DROP DATABASE IF EXISTS shopsphere;
CREATE DATABASE shopsphere CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shopsphere;
CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, phone VARCHAR(30), full_name VARCHAR(120) NULL, address VARCHAR(255) NULL, city VARCHAR(80) NULL, state VARCHAR(80) NULL, postal_code VARCHAR(20) NULL, country VARCHAR(80) NULL, profile_image VARCHAR(500) NULL, profile_image_data MEDIUMBLOB NULL, profile_image_mime VARCHAR(50) NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(email));
CREATE TABLE admins (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, slug VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(255));
CREATE TABLE brands (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE);
CREATE TABLE products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, brand_id INT UNSIGNED NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL UNIQUE, description TEXT NOT NULL, specifications JSON NULL, image_url VARCHAR(500) NOT NULL, price DECIMAL(10,2) NOT NULL, compare_price DECIMAL(10,2) NULL, stock INT NOT NULL DEFAULT 0, rating DECIMAL(2,1) NOT NULL DEFAULT 4.5, sold_count INT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES categories(id), FOREIGN KEY(brand_id) REFERENCES brands(id), INDEX(category_id), INDEX(price));
CREATE TABLE product_images (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NOT NULL, image_url VARCHAR(500) NOT NULL, sort_order TINYINT DEFAULT 0, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE carts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL UNIQUE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE cart_items (cart_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, quantity INT NOT NULL DEFAULT 1, PRIMARY KEY(cart_id, product_id), FOREIGN KEY(cart_id) REFERENCES carts(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE wishlists (user_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id, product_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE orders (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_number VARCHAR(30) NOT NULL UNIQUE, user_id INT UNSIGNED NOT NULL, status ENUM('Pending','Confirmed','Processing','Shipped','Delivered','Refunded','Cancelled') DEFAULT 'Pending', subtotal DECIMAL(10,2) NOT NULL, shipping DECIMAL(10,2) NOT NULL, discount DECIMAL(10,2) DEFAULT 0, total DECIMAL(10,2) NOT NULL, payment_method VARCHAR(40) NOT NULL, billing_json JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), INDEX(user_id,status));
CREATE TABLE order_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, product_name VARCHAR(180) NOT NULL, unit_price DECIMAL(10,2) NOT NULL, quantity INT NOT NULL, FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE reviews (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, rating TINYINT NOT NULL, title VARCHAR(120), body TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE returns (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, reason VARCHAR(120) NOT NULL, details TEXT, status ENUM('Requested','Approved','Rejected','Refunded') NOT NULL DEFAULT 'Requested', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(order_id,user_id));
CREATE TABLE coupons (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(30) UNIQUE NOT NULL, discount_percent TINYINT NOT NULL, expires_at DATE NOT NULL, is_active TINYINT(1) DEFAULT 1);
CREATE TABLE newsletter_subscribers (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) UNIQUE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO admins(name,email,password_hash) VALUES('ShopSphere Admin','admin@shopsphere.test','$2y$10$j9uZKKco.mcXd45SWO5rteKZR3Ifj8GM7qN74JOzG9dJuRQMK3rxC');
INSERT INTO categories(name,slug,description) VALUES ('Home & Living','home-living','Objects that make home feel like home'),('Tech Essentials','tech-essentials','Useful tools for modern routines'),('Style','style','Everyday pieces with a point of view'),('Wellness','wellness','Small rituals, better days'),('Outdoor','outdoor','For time well spent outside');
INSERT INTO categories(name,slug,description) VALUES ('Kitchen','kitchen','Tools for slower, better meals'),('Books & Paper','books-paper','Pages and paper for ideas worth keeping');
INSERT INTO categories(name,slug,description) VALUES ('Travel','travel','Useful companions for going farther'),('Pets','pets','Thoughtful essentials for four-legged friends'),('Gifts','gifts','Small, considered gifts for good people');
INSERT INTO brands(name) VALUES ('Northstar'),('Hearth & Hand'),('Field Notes'),('Aster');
INSERT INTO products(category_id,brand_id,name,slug,description,image_url,price,compare_price,stock,rating,sold_count) VALUES
(1,1,'Stoneware Pour-Over Set','stoneware-pour-over-set','A calm morning ritual in matte ceramic. Includes dripper and carafe.','https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800',48,64,24,4.8,210),
(2,1,'Arc Wireless Headphones','arc-wireless-headphones','Balanced sound, soft memory foam, and 36 hours of quiet listening.','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',129,159,18,4.7,342),
(3,3,'Canvas Utility Tote','canvas-utility-tote','A structured, durable carry-all cut from heavy organic canvas.','https://images.unsplash.com/photo-1544816155-12df9643f363?w=800',36,44,45,4.6,198),
(4,4,'Daily Reset Journal','daily-reset-journal','A 90-day guided journal for clearer thinking and softer starts.','https://images.unsplash.com/photo-1517842645767-c639042777db?w=800',22,28,60,4.9,420),
(5,3,'Trail Bottle 750ml','trail-bottle','Double-wall insulated steel bottle, built for long afternoons outdoors.','https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800',28,35,35,4.8,177),
(1,2,'Linen Lounge Throw','linen-lounge-throw','Washed linen with a little weight and a lot of comfort.','https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800',74,92,12,4.5,82),
(2,1,'Desk Light Mini','desk-light-mini','Warm, dimmable light for focused corners and late ideas.','https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',58,70,15,4.6,105),
(3,4,'Everyday Overshirt','everyday-overshirt','A relaxed layer in brushed cotton with considered utility pockets.','https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',89,110,20,4.4,65),
(4,2,'Cloud Bath Salts','cloud-bath-salts','Mineral-rich salts scented with cedar, bergamot, and clean air.','https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800',19,24,32,4.8,250),
(5,3,'Camp Blanket','camp-blanket','A generous recycled-wool blanket for parks, porches, and road trips.','https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800',98,120,8,4.7,44);
INSERT INTO products(category_id,brand_id,name,slug,description,image_url,price,compare_price,stock,rating,sold_count) VALUES
(1,2,'Oak Catchall Tray','oak-catchall-tray','A simple landing place for keys, coins, and the little things.','https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800',32,40,28,4.6,91),
(2,4,'Pocket Power Bank','pocket-power-bank','A slim 10,000mAh charger that disappears into your everyday carry.','https://images.unsplash.com/photo-1609592424850-2c2e7f2b8a9b?w=800',39,49,40,4.5,146),
(3,1,'Ribbed Everyday Socks','ribbed-everyday-socks','Soft organic cotton socks with just enough structure.','https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=800',16,20,75,4.7,320),
(4,4,'Essential Face Mist','essential-face-mist','A light botanical mist for a quick reset between moments.','https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800',24,30,26,4.4,104),
(5,3,'Day Hike Cap','day-hike-cap','A breathable, low-profile cap for bright days and long walks.','https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800',29,36,31,4.6,125),
(1,1,'Wool Blend Cushion','wool-blend-cushion','Textured comfort in a warm, naturally durable blend.','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',42,55,16,4.5,72),
(2,2,'Focus Timer','focus-timer','A tactile desk timer for a calmer approach to focused work.','https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800',31,38,22,4.3,58),
(3,4,'Minimal Card Wallet','minimal-card-wallet','Slim leather-free wallet with room for the essentials.','https://images.unsplash.com/photo-1627123424574-724758594e93?w=800',27,35,34,4.8,188),
(4,2,'Cedar Candle','cedar-candle','A clean-burning candle with cedar, smoke, and soft amber notes.','https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800',26,34,19,4.7,211),
(5,1,'Packable Picnic Mat','packable-picnic-mat','Water-resistant, easy to fold, and ready for the next open patch of grass.','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',64,78,11,4.6,66);
INSERT INTO products(category_id,brand_id,name,slug,description,specifications,image_url,price,compare_price,stock,rating,sold_count) VALUES
(6,2,'Brass Measuring Spoon Set','brass-measuring-spoons','A nesting set that brings a little ceremony to everyday cooking.', '{"Material":"Brushed stainless steel","Includes":"4 nesting spoons","Care":"Hand wash recommended"}','https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800',24,30,40,4.7,74),
(6,1,'Stoneware Prep Bowls','stoneware-prep-bowls','Three stackable bowls for mise en place, snacks, and small servings.', '{"Material":"Glazed stoneware","Includes":"3 stackable bowls","Capacity":"250ml each"}','https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',38,46,22,4.8,61),
(6,3,'Linen Kitchen Apron','linen-kitchen-apron','A durable cross-back apron in washed linen that softens with use.', '{"Material":"100% washed linen","Fit":"Adjustable cross-back","Care":"Machine wash cold"}','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',46,58,18,4.6,53),
(7,3,'The Daily Notes Pad','daily-notes-pad','A tear-off pad for lists, loose thoughts, and plans that need room.', '{"Pages":"80 tear-off sheets","Paper":"Recycled 100gsm paper","Size":"A5"}','https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800',14,18,80,4.9,144),
(7,4,'Clothbound Reading Journal','clothbound-reading-journal','A considered place to keep the books, lines, and ideas you return to.', '{"Pages":"160 lined pages","Cover":"Clothbound hardcover","Size":"A5"}','https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',26,34,35,4.8,97),
(7,1,'Desk Calendar 2027','desk-calendar-2027','A simple weekly desk calendar for making space for what matters next.', '{"Pages":"53 weekly pages","Paper":"FSC-certified paper","Format":"Desktop easel"}','https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800',21,27,50,4.5,36);
INSERT INTO products(category_id,brand_id,name,slug,description,specifications,image_url,price,compare_price,stock,rating,sold_count) VALUES
(8,1,'Weekender Travel Bag','weekender-travel-bag','A roomy canvas carryall with a structured base for short escapes.', '{"Material":"Organic cotton canvas","Capacity":"32 litres","Care":"Spot clean"}','https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',86,110,24,4.8,83),
(8,3,'Passport Organizer','passport-organizer','A slim organizer for passport, cards, and the little papers that matter.', '{"Material":"Vegetable-tanned leather","Capacity":"Passport and 4 cards","Closure":"Zip"}','https://images.unsplash.com/photo-1581553680321-4fffae59fccd?w=800',34,42,38,4.6,91),
(8,4,'Travel Eye Mask','travel-eye-mask','Soft, light-blocking comfort for trains, planes, and early mornings.', '{"Material":"Washed cotton","Filling":"Recycled fiber","Care":"Machine wash cold"}','https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',18,24,55,4.5,67),
(9,3,'Woven Pet Bed','woven-pet-bed','A supportive woven bed that gives quiet corners a softer landing.', '{"Material":"Recycled cotton","Size":"Medium","Cover":"Removable and washable"}','https://images.unsplash.com/photo-1581888227599-779811939961?w=800',72,88,16,4.9,54),
(9,2,'Ceramic Pet Bowl','ceramic-pet-bowl','A steady, easy-clean bowl with a calm glazed finish.', '{"Material":"Glazed stoneware","Capacity":"700ml","Care":"Dishwasher safe"}','https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800',28,36,29,4.7,88),
(9,1,'Everyday Lead','everyday-lead','A dependable woven lead with a comfortable hand loop for daily walks.', '{"Material":"Recycled webbing","Length":"1.5 metres","Hardware":"Brushed metal clasp"}','https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800',24,30,42,4.6,72),
(10,4,'Sunday Candle Trio','sunday-candle-trio','Three small candles in warm, everyday scents, ready to give.', '{"Includes":"3 travel candles","Burn time":"20 hours each","Wax":"Soy wax"}','https://images.unsplash.com/photo-1602607205817-7d0a14c15f73?w=800',32,40,34,4.8,101),
(10,2,'Desk Ritual Gift Box','desk-ritual-gift-box','A useful little collection for clear thinking and slower workdays.', '{"Includes":"Notebook, pen, and candle","Packaging":"Plastic-free","Best for":"Thoughtful gifting"}','https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',48,60,21,4.7,64),
(10,3,'Morning Tea Gift Set','morning-tea-gift-set','A gentle morning set with a ceramic cup, tea towel, and loose leaf tea.', '{"Includes":"Cup, towel, and tea","Tea":"Earl Grey","Packaging":"Gift-ready"}','https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800',42,52,27,4.9,79),
(8,1,'Foldable Market Tote','foldable-market-tote','A compact reusable tote that opens up when the day asks for more.', '{"Material":"Ripstop recycled nylon","Capacity":"18 litres","Folded size":"Pocket-sized"}','https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=800',19,25,65,4.6,120),
(9,4,'Soft Knit Pet Toy','soft-knit-pet-toy','A durable, quiet knit toy for gentle play at home.', '{"Material":"Organic cotton knit","Size":"Small","Care":"Surface wash"}','https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=800',15,20,70,4.5,93),
(10,1,'Handwritten Note Set','handwritten-note-set','Thick textured cards and envelopes for messages worth sending.', '{"Includes":"12 cards and envelopes","Paper":"Recycled cotton paper","Size":"A6"}','https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800',17,22,90,4.8,132);
INSERT INTO users(name,email,phone,password_hash) VALUES('Demo Customer','demo@shopsphere.test','+91 90000 00000','$2y$10$0JDKSXFq2uqwlha5DRYi4uRgB6oTTv2XEdmTKPKvn2.AJr38I/l26');
INSERT INTO coupons(code,discount_percent,expires_at) VALUES('RESET15',15,'2027-12-31');
INSERT INTO reviews(product_id,user_id,rating,title,body) VALUES(1,1,5,'A beautiful daily ritual','The ceramic feels lovely and the pour is exceptionally calm.'),(2,1,5,'Comfortable for long sessions','Clear sound and no pressure on the ears.'),(4,1,4,'A thoughtful companion','The prompts are short enough to actually keep up with.');
INSERT INTO orders(order_number,user_id,status,subtotal,shipping,discount,total,payment_method,billing_json) VALUES('SS-DEMO-1001',1,'Delivered',70.00,7.95,0,77.95,'Cash on Delivery','{"full_name":"Demo Customer","email":"demo@shopsphere.test","phone":"+91 90000 00000","address":"12 Sample Street","city":"Pune","state":"Maharashtra","postal_code":"411001","country":"India"}');
INSERT INTO order_items(order_id,product_id,product_name,unit_price,quantity) VALUES(1,1,'Stoneware Pour-Over Set',48.00,1),(1,4,'Daily Reset Journal',22.00,1);
